### ISSUE TITLE
How to walk

### ISSUE THREAD

**Issue by manipulability** [saga0619/dyros_tocabi_v2#15]
Thank you for sharing your source code.
The installation and execution of the simulator were successfully completed.
But could you let me know how to walk?

When I press the 'State estimation' button on the UI, and the click the 'walking init' or 'walking start' button, the robot diverges and dances.

![image](https://user-images.githubusercontent.com/39412468/149453098-442bcb84-9f0f-4f73-86fa-8de09c8092b6.png)

**Comment by saga0619** [comment]
walking algorithm is not implemented in current algorithm.
